version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - minio
      - mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
