version: '3.9'
services:
  nextjs-app:
    container_name: pdf-gpt-nextjs-app-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - minio
      - mysql

  minio:
    image: minio/minio
    container_name: pdf-gpt-my-minio-v1
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: [ "server", "--console-address", ":9001", "/data" ]
    network_mode: host

  mysql:
    image: mysql:8
    container_name: pdf-gpt-my-mysql-v1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  minio-data:
  mysql-data:
