version: '3.9'
services:
  minio:
    image: minio/minio
    container_name: pdf-gpt-my-minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: [ "server", "--console-address", ":9001", "/data" ]
    network_mode: host

  mysql:
    image: mysql:8
    container_name: pdf-gpt-my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password

  adminer:
    container_name: pdf-gpt-adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  minio-data:
  mysql-data:
